### ISSUE TITLE
Adicionar página de erro 404 e 500

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde-webpage#3]

**Comment by talitanovacoski** [comment]
**Contexto:** Devido à queda do BONDE na segunda-feira, o Rodrigo levantou a necessidade de desenvolvermos uma página de erro que dê um direcionamento aos usuários e melhore essa experiência.

**Solução:** Desenvolver duas páginas de erro padrão para os erros 404 e 500 no bonde-webpage.

**Design:** https://www.figma.com/file/qA1zfMuYGEKCA41hGvuSRR/BONDE-Erro?node-id=0%3A1

**Comment by igr-santos** [comment]
@lpirola atualizado as páginas no ambiente de staging, mas temos um problema que está relacionado ao ambiente Traefik + Bonde Public. Quando eu estou no ambiente local quem trata a primeira requisição é o Next, quando estou no ambiente de staging quem trata a primeira requisição é o Traefik, quando o Traefik recebe 500 da aplicação ele não renderiza a página do Next e sim uma página padrão de erro do Traefik, preciso entender melhor se consigo informar pro Traefik que minha aplicação trata esse erro e ele deve renderizar a minha resposta.

**Comment by talitanovacoski** [comment]
@igr-santos Conferindo a pagina 404 em staging aqui vi uma correção: 
- Ajustar o margin-top do conteúdo de 120px para 60px.
